doc(core): update credentials links
scaleway/scaleway-cli pull request #1419
Opened 2020-09-11 12:20 UTC by QuentinBrosse

**Do not merge.**

2020-09-11 13:22 UTC, remyleone approved these changes

2020-09-11 14:06 UTC, kindermoumoute requested changes

2020-09-11 14:06 UTC, kindermoumoute commented on internal/namespaces/config/commands.go
> +		{"|", scw.ScwDefaultOrganizationIDEnv, "|", "The default organization ID (get your organization ID at https://console.scaleway.com/project/credentials)", "|"},
add project id

2020-09-15 08:52 UTC, jerome-quere approved these changes

2020-09-15 08:54 UTC, merged