fix(account): remove GetLogin
scaleway/scaleway-cli pull request #2328
Opened 2022-05-17 13:42 UTC by remyleone

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Release note for [CHANGELOG](https://github.com/scaleway/scaleway-cli/blob/master/CHANGELOG.md):

```release-note

```

2022-05-17 13:50 UTC, kindermoumoute requested changes

2022-05-17 13:50 UTC, kindermoumoute commented on internal/namespaces/init/init.go
>  	}
Update prompted information "Enter a valid secret-key or an email" ==> "Enter a valid secret-key"

2022-05-17 13:50 UTC, kindermoumoute commented on internal/namespaces/init/init.go
Can we ask for access key too?

2022-05-17 14:08 UTC, kindermoumoute submitted a review, later dismissed
LGTM

2022-05-17 16:14 UTC, remyleone commented on internal/namespaces/init/testdata/test-init-ssh-with-local-ed25519-key.cassette.yaml
> +    body: '{"details":[{"argument_name":"public_key","help_message":"invalid key format:
@sweenu @kindermoumoute Do you know if additional checks are performed on your side now?

2022-05-18 15:39 UTC, kindermoumoute approved these changes

2022-05-18 15:40 UTC, merged