feat(config): add output default format
scaleway/scaleway-cli pull request #3003
Opened 2023-04-05 14:06 UTC by yfodil

2023-04-05 14:49 UTC, quantumsheep requested changes

2023-04-05 14:49 UTC, quantumsheep commented on internal/config/config.go
> +       {{- end }}
```suggestion
        {{- end }}
```

2023-04-05 14:49 UTC, quantumsheep commented on internal/config/config.go
> +{{ end }}
```suggestion
{{- end -}}
```

2023-04-05 14:49 UTC, quantumsheep commented on internal/core/bootstrap.go
> +	if *cliCfg.Output != cliConfig.DefaultOutput && *cliCfg.Output != "" {
```suggestion
	if *cliCfg.Output != cliConfig.DefaultOutput {
```

2023-04-05 14:49 UTC, quantumsheep commented on internal/config/config.go
> +	Output *string       `json:"output"`
Why is it a pointer if it's mandatory?

2023-04-05 14:49 UTC, quantumsheep commented on internal/core/bootstrap.go
> +			_, _ = fmt.Fprintln(config.Stderr, err)
```suggestion
			fmt.Fprintln(config.Stderr, err)
```

I don't think it's required with `fmt.Fprintln`

2023-04-06 08:11 UTC, quantumsheep approved these changes

2023-04-06 08:32 UTC, Codelax commented on internal/config/config.go
> +`
Make sure the created file has a newline at the end

2023-04-06 08:34 UTC, Codelax requested changes
Comment made outside the review

2023-04-06 12:14 UTC, Codelax approved these changes

2023-04-06 15:22 UTC, Codelax approved these changes

2023-04-06 15:30 UTC, merged